version: "3.8"

services:
  mongo:
    build:
      context: ./services/mongodb
      args:
        MONGO_VERSION: 6
    environment:
      MONGO_REPLICA_PORT: 27017
      MONGO_REPLICA_HOST: mongo-dapp-container
      MONGO_COMMAND: "mongosh"
      MONGO_INITDB_ROOT_USERNAME: dappAdmin
      MONGO_INITDB_ROOT_PASSWORD: S3cur3P@ssw0rdM0ng0
    container_name: mongo-dapp-container
    restart: unless-stopped
    networks:
      - dapp_network
    ports:
      - "27017:27017"
    volumes:
      - ./volumes/mongo_data:/data/db

  mysql:
    image: mysql:latest
    container_name: mysql-dapp-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: S3cur3P@ssw0rdMySQL
      MYSQL_DATABASE: dapp_database
      MYSQL_USER: dapp_user
      MYSQL_PASSWORD: S3cur3D@ppUs3r
    ports:
      - "3306:3306"
    volumes:
      - ./volumes/mysql_data:/var/lib/mysql
    networks:
      - dapp_network

  dapp-core-ms:
    build:
      context: ./apps/dapp-core-ms
    container_name: dapp-core-ms-container
    env_file:
      - ./apps/dapp-core-ms/.env
    ports:
      - "3001:3001"
    depends_on:
      - mongo
    networks:
      - dapp_network

  dapp-etl-ms:
    build:
      context: ./apps/dapp-etl-ms
    container_name: dapp-etl-ms-container
    env_file:
      - ./apps/dapp-etl-ms/.env
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    networks:
      - dapp_network

networks:
  dapp_network:
    driver: bridge

volumes:
  mongo_data:
    driver: local
  mysql_data:
    driver: local
