version: "3.8"

services:
  mongo:
    build:
      context: ./services/mongodb
      args:
        MONGO_VERSION: 6
    environment:
      MONGO_REPLICA_PORT: 27017
      MONGO_REPLICA_HOST: mongo-dapp-container
      MONGO_COMMAND: "mongosh"
      MONGO_INITDB_ROOT_USERNAME: dappAdmin
      MONGO_INITDB_ROOT_PASSWORD: S3cur3P@ssw0rdM0ng0
    container_name: mongo-dapp-container
    restart: unless-stopped
    networks:
      - dapp_network
    ports:
      - "27017:27017"
    volumes:
      - ./volumes/mongo_data:/data/db

  mysql:
    image: mysql:8.0
    container_name: mysql-dapp-container
    restart: always
    environment:
      MYSQL_DATABASE: dapp_database
      MYSQL_ROOT_PASSWORD: rootADDmin
      MYSQL_USER: rootADDmin
      MYSQL_PASSWORD: rootADDmin
    ports:
      - "3306:3306"
    volumes:
      - ./volumes/mysql_data:/var/lib/mysql
      # - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - dapp_network

  dapp-core-ms:
    build:
      context: ./apps/dapp-core-ms
    container_name: dapp-core-ms-container
    env_file:
      - ./apps/dapp-core-ms/.env
    ports:
      - "3001:3001"
    depends_on:
      - mongo
    networks:
      - dapp_network

  dapp-auth-ms:
    build:
      context: ./apps/dapp-auth-ms
    container_name: dapp-auth-ms-container
    restart: always
    env_file:
      - ./apps/dapp-auth-ms/.env
    ports:
      - "3002:3002"
    depends_on:
      - mysql
    networks:
      - dapp_network

  dapp-etl-ms:
    build:
      context: ./apps/dapp-etl-ms
    container_name: dapp-etl-ms-container
    env_file:
      - ./apps/dapp-etl-ms/.env
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    networks:
      - dapp_network

  nginx:
    image: nginx:latest
    container_name: nginx-gateway
    ports:
      - "4000:4000"
    volumes:
      - ./services/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - dapp-core-ms
      - dapp-auth-ms
    networks:
      - dapp_network

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    privileged: true
    ports:
      - "9090:9090"
    networks:
      - dapp_network

  cadvisor:
    image: gcr.io/google-containers/cadvisor:latest
    container_name: cadvisor
    privileged: true
    ports:
      - "8080:8080"
    volumes:
      - /:/rootfs
      - /var/run:/var/run
      - /sys:/sys
      - /var/lib/docker/:/var/lib/docker
      - /dev/disk/:/dev/disk
    networks:
      - dapp_network
    devices:
      - "/dev/kmsg"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3100:3000"
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - DS_PROMETHEUS=prometheus
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./monitoring/grafana/dashboards:/var/lib/grafana/dashboards
      - ./monitoring/grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
    networks:
      - dapp_network
    privileged: true
    depends_on:
      - prometheus

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    ports:
      - "9100:9100" # Puerto donde escucha Node Exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - "--path.procfs=/host/proc"
      - "--path.sysfs=/host/sys"
      - '--collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($|/)"'
    networks:
      - dapp_network
    privileged: true

  mongo-exporter:
    image: percona/mongodb_exporter:0.42
    container_name: mongo-exporter
    restart: always
    ports:
      - "9216:9216"
    command:
      - "--mongodb.global-conn-pool"
      - "--collector.diagnosticdata"
      - "--discovering-mode"
      - "--compatible-mode"
      - "--mongodb.collstats-colls=admin.dapp_database"
    networks:
      - dapp_network
    environment:
      WAIT_HOSTS: mongo-dapp-container:27017
      MONGODB_URI: mongodb://dappAdmin:S3cur3P%40ssw0rdM0ng0@mongo-dapp-container:27017/dapp?authSource=admin&directConnection=true
    depends_on:
      - mongo
networks:
  dapp_network:
    driver: bridge

volumes:
  grafana_data:
    driver: local
  mongo_data:
    driver: local
  mysql_data:
    driver: local
